project:
  type: website
  output-dir: docs

website:
  title: "Test Giscus"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    toc: true
    css: assets/cobalt.css
    comments:
      giscus: 
        repo: r-leyshon/quarto-giscus
        repo-id: R_kgDOMkzHGg
        category: Announcements
        category-id: DIC_kwDOMkzHGs4ChvwI
        reactions-enabled: false
        mapping: url
        theme: "url:https://fischerpj.github.io/qwgsc/assets/cobalt.css"